name: Build Windows Executable (Simple)

on:
  push:
    branches: [ main, master ]
  workflow_dispatch: # Allow manual triggering

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build Next.js app
      run: npm run build
      
    - name: Build Windows executable
      run: npm run electron:dist-win
      
    - name: Upload Windows executable
      uses: actions/upload-artifact@v4
      with:
        name: police-app-windows-exe
        path: dist/*.exe
        retention-days: 30 